name: Gallery Release
on:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        platform: [macOS-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Parse Event
        run: |
          echo "tag=$(jq -r '.release.tag_name' "${GITHUB_EVENT_PATH}" | sed s/^v//)" >> $GITHUB_ENV
      - name:  Build and pack
        run: |
          # pack
          cd .workflow
          plutil -replace version -string "${{ env.tag }}" info.plist
          zip -r ../"AlfredSymlink_GALLERY-${{ env.tag }}.alfredworkflow" .
          cd ..

          echo "artifact=$(echo "AlfredSymlink_GALLERY-${{ env.tag }}.alfredworkflow")" >> $GITHUB_ENV 
      - uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: "${{ env.artifact }}"
